version: "3.9"
services:
  app:
    build: .
    ports:
      - "8081:8081"
  chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
      - "7900:7900"
    environment:
      SE_NODE_MAX_SESSIONS: 10
      SE_NODE_OVERRIDE_MAX_SESSIONS: "true"
    shm_size: '2g'